/// Second copy of the link bridge - chained to Bridge Issue Link to give the SECOND hop (an issue's links' links)
table 'Bridge Issue Link (2)'
	lineageTag: 4d9c2b70-1a5e-4f83-9c26-8b7d6e5f0a12

	column 'Issue Code'
		dataType: string
		lineageTag: 5ead3c81-2b6f-4094-ad37-9c8e7f601b23
		summarizeBy: none
		sourceColumn: Issue Code

		annotation SummarizationSetBy = Automatic

	column 'Link Label'
		dataType: string
		lineageTag: 6fbe4d92-3c70-41a5-be48-ad9f80712c34
		summarizeBy: none
		sourceColumn: Link Label

		annotation SummarizationSetBy = Automatic

	column 'Link Type Name'
		dataType: string
		lineageTag: 70cf5ea3-4d81-42b6-cf59-be0f91823d45
		summarizeBy: none
		sourceColumn: Link Type Name

		annotation SummarizationSetBy = Automatic

	column 'Linked Issue Code'
		dataType: string
		lineageTag: 81d06fb4-5e92-43c7-d06a-cf10a2934e56
		summarizeBy: none
		sourceColumn: Linked Issue Code

		annotation SummarizationSetBy = Automatic

	column 'Linked Issue Type'
		dataType: string
		lineageTag: 92e170c5-6fa3-44d8-e17b-d021b3a45f67
		summarizeBy: none
		sourceColumn: Linked Issue Type

		annotation SummarizationSetBy = Automatic

	column 'Linked Issue Summary'
		dataType: string
		lineageTag: a3f281d6-70b4-45e9-f28c-e132c4b56078
		summarizeBy: none
		sourceColumn: Linked Issue Summary

		annotation SummarizationSetBy = Automatic

	partition 'Bridge Issue Link (2)' = m
		mode: import
		source =
				let
				  Source = Sql.Database("cekvmk67pvoetale6vvoo5wfji-brlvcnhvridetpgxmhh6wmlcw4.datawarehouse.fabric.microsoft.com", "gold"),
				  #"Navigation 1" = Source{[Schema = "gold", Item = "bridge_issue_link"]}[Data],
				  RenamedColumns = Table.TransformColumnNames( #"Navigation 1", each Text.Replace(_, "_", " ")),
				  #"Kept Columns" = Table.SelectColumns(RenamedColumns, {"Issue Code", "Link Label", "Link Type Name", "Linked Issue Code", "Linked Issue Type", "Linked Issue Summary"})
				in
				    #"Kept Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation
