table 'Bridge Issue Link'
	lineageTag: c9e118c1-4448-4d93-b16f-9a63f69d58a6

	column Direction
		dataType: string
		lineageTag: fe57d8d7-ca08-46f8-8ed5-9e31a7405d79
		summarizeBy: none
		sourceColumn: Direction

		annotation SummarizationSetBy = Automatic

	column 'Issue Code'
		dataType: string
		lineageTag: 328571d8-22ae-41fc-bfa5-8f76c7930bbb
		summarizeBy: none
		sourceColumn: Issue Code

		annotation SummarizationSetBy = Automatic

	column 'Linked Issue Code'
		dataType: string
		lineageTag: 78a6aa9e-94a5-46ac-9540-f00467e27f13
		summarizeBy: none
		sourceColumn: Linked Issue Code

		annotation SummarizationSetBy = Automatic

	column 'Link Type Name'
		dataType: string
		lineageTag: 8fb6d8e6-5b22-49ba-abc4-527f941a45fd
		summarizeBy: none
		sourceColumn: Link Type Name

		annotation SummarizationSetBy = Automatic

	column 'Link Label'
		dataType: string
		lineageTag: 892906ac-f9d6-42a2-98a1-6c8ac4665e1a
		summarizeBy: none
		sourceColumn: Link Label

		annotation SummarizationSetBy = Automatic

	column 'Issue Key'
		dataType: string
		isHidden
		lineageTag: d3cfda82-a648-4357-8f57-c0db84a2b6f7
		summarizeBy: none
		sourceColumn: Issue Key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Linked Issue Key'
		dataType: string
		isHidden
		lineageTag: 7b1d9717-a78b-4705-bc87-40c494b6ec24
		summarizeBy: none
		sourceColumn: Linked Issue Key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Link Type Key'
		dataType: string
		isHidden
		lineageTag: 4f95b533-7a1f-4cec-ae36-ae0075527d23
		summarizeBy: none
		sourceColumn: Link Type Key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Issue Link Key'
		dataType: string
		isHidden
		lineageTag: 6f841ec6-00ed-4555-8584-3ad7927ad280
		summarizeBy: none
		sourceColumn: Issue Link Key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Linked Issue Summary'
		dataType: string
		lineageTag: 413004bc-48cb-40bc-9a6e-f5f1a16d1cfb
		summarizeBy: none
		sourceColumn: Linked Issue Summary

		annotation SummarizationSetBy = Automatic

	column 'Linked Issue Status'
		dataType: string
		lineageTag: 5f2a1b6c-7d8e-4901-a2b3-c4d5e6f70812
		summarizeBy: none
		sourceColumn: Linked Issue Status

		annotation SummarizationSetBy = Automatic

	column 'Linked Test Status'
		dataType: string
		lineageTag: 43467fe6-72fd-4d1f-8eec-8bc421ac468d
		summarizeBy: none
		sourceColumn: Linked Test Status

		annotation SummarizationSetBy = Automatic

	column 'Issue Test Status'
		dataType: string
		lineageTag: 6a3b2c7d-8e9f-4012-b3c4-d5e6f7081923
		summarizeBy: none
		sourceColumn: Issue Test Status

		annotation SummarizationSetBy = Automatic

	column 'Test Status Key'
		dataType: string
		isHidden
		lineageTag: c5070907-6c25-4056-8f8b-8d07d565030c
		summarizeBy: none
		sourceColumn: Test Status Key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Project Key'
		dataType: string
		isHidden
		lineageTag: e3d15016-8e33-4f1d-9f9e-273f5a277b0c
		summarizeBy: none
		sourceColumn: Project Key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Team Key'
		dataType: string
		isHidden
		lineageTag: 183077a7-d962-47c7-8c98-f8a77ff3e18d
		summarizeBy: none
		sourceColumn: Team Key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Linked Issue Type'
		dataType: string
		lineageTag: d10884f2-ba68-4443-90ae-0c5ecc8634e1
		summarizeBy: none
		sourceColumn: Linked Issue Type

		annotation SummarizationSetBy = Automatic

	column 'Linked Issue Acceptance Criteria'
		dataType: string
		lineageTag: 8fb97286-c3e7-4447-955f-2fdaea07c528
		summarizeBy: none
		sourceColumn: Linked Issue Acceptance Criteria

		annotation SummarizationSetBy = Automatic

	column 'Linked Issue URL'
		dataType: string
		lineageTag: 37012573-ac76-4711-92e6-c86342bbfab5
		dataCategory: WebUrl
		summarizeBy: none
		sourceColumn: Linked Issue URL

		annotation SummarizationSetBy = Automatic

	partition 'Bridge Issue Link' = m
		mode: import
		source =
				let
				    Source = Sql.Database("cekvmk67pvoetale6vvoo5wfji-brlvcnhvridetpgxmhh6wmlcw4.datawarehouse.fabric.microsoft.com", "gold"),
				    gold_bridge_issue_link = Source{[Schema="gold",Item="bridge_issue_link"]}[Data],
				    RenamedColumns = Table.TransformColumnNames(gold_bridge_issue_link, each Text.Replace(_, "_", " ")),
				    CapitalizedLinkLabel = Table.TransformColumns(RenamedColumns,{{"Link Label", Text.Proper, type text}})
				in
				    CapitalizedLinkLabel

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

