/// Dim Issue table
table 'Dim Issue'
	lineageTag: 6528fd07-43e1-4454-aa11-6acf084320b5

	column 'Issue Id'
		dataType: string
		isHidden
		lineageTag: 545c3f08-9077-41ef-831a-fc7366344462
		summarizeBy: none
		sourceColumn: Issue Id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Issue Code'
		dataType: string
		lineageTag: 58bd33fe-ab29-4f22-af25-e7a07c16c390
		summarizeBy: none
		sourceColumn: Issue Code

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Parent Issue Id'
		dataType: string
		isHidden
		lineageTag: 2ac98fae-3ff5-4231-b730-cbe6b4243f95
		summarizeBy: none
		sourceColumn: Parent Issue Id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Issue Key'
		dataType: string
		isHidden
		lineageTag: 6b30937b-a12f-47f1-9934-773f542978d4
		summarizeBy: none
		sourceColumn: Issue Key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Level 1'
		dataType: string
		displayFolder: Gantt Chart Fields\Levels
		lineageTag: c0fc7b68-31c6-4ed2-b404-782b13b0c659
		summarizeBy: none
		sourceColumn: Level 1

		annotation SummarizationSetBy = Automatic

	column 'Level 2'
		dataType: string
		displayFolder: Gantt Chart Fields\Levels
		lineageTag: 91fc0582-a61c-4a70-a8f4-f97f438155fd
		summarizeBy: none
		sourceColumn: Level 2

		annotation SummarizationSetBy = Automatic

	column 'Level 3'
		dataType: string
		displayFolder: Gantt Chart Fields\Levels
		lineageTag: b5a66700-f596-47dc-87b0-3ce1371890b0
		summarizeBy: none
		sourceColumn: Level 3

		annotation SummarizationSetBy = Automatic

	column 'Level 4'
		dataType: string
		displayFolder: Gantt Chart Fields\Levels
		lineageTag: 448e67f1-5cff-416b-9c42-3a633711e9f1
		summarizeBy: none
		sourceColumn: Level 4

		annotation SummarizationSetBy = Automatic

	column 'Level 5'
		dataType: string
		displayFolder: Gantt Chart Fields\Levels
		lineageTag: 34023874-e41f-4edd-96de-d1c085524092
		summarizeBy: none
		sourceColumn: Level 5

		annotation SummarizationSetBy = Automatic

	column 'Level 6'
		dataType: string
		displayFolder: Gantt Chart Fields\Levels
		lineageTag: 640f2a23-becf-4b8b-9eb8-22715fec56fe
		summarizeBy: none
		sourceColumn: Level 6

		annotation SummarizationSetBy = Automatic

	column 'Level 7'
		dataType: string
		displayFolder: Gantt Chart Fields\Levels
		lineageTag: 2d12e591-a5e6-4791-8a21-ce56c0a5b44a
		summarizeBy: none
		sourceColumn: Level 7

		annotation SummarizationSetBy = Automatic

	column 'Sort Path'
		dataType: string
		isHidden
		lineageTag: a4aeca72-a3c0-4de3-be5d-d224ba2ca0cc
		summarizeBy: none
		sourceColumn: Sort Path

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Lead Name'
		dataType: string
		lineageTag: 40f267cc-a932-43c1-af27-32bb0e462696
		summarizeBy: none
		sourceColumn: Lead Name

		annotation SummarizationSetBy = Automatic

	column 'Resource Names'
		dataType: string
		displayFolder: Gantt Chart Fields
		lineageTag: c310b928-6a24-47fa-977c-6e3722225591
		summarizeBy: none
		sourceColumn: Resource Names

		annotation SummarizationSetBy = Automatic

	column 'Is Milestone'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: f89ab70c-264d-4339-b06b-18bada0a20cf
		summarizeBy: none
		sourceColumn: Is Milestone

		annotation SummarizationSetBy = Automatic

	column 'Predecessor Issue Code'
		dataType: string
		lineageTag: ae53c5e4-993e-4f65-9b0a-d2c5c62f5b02
		summarizeBy: none
		sourceColumn: Predecessor Issue Code

		annotation SummarizationSetBy = Automatic

	column 'Issue Type Name'
		dataType: string
		lineageTag: 3bbae582-655d-48ba-b368-095bf9ac36fe
		summarizeBy: none
		sourceColumn: Issue Type Name

		annotation SummarizationSetBy = Automatic

	column 'Status Name'
		dataType: string
		lineageTag: 1028db72-577d-4307-ade0-43e899c94bba
		summarizeBy: none
		sourceColumn: Status Name

		annotation SummarizationSetBy = Automatic

	column 'Priority Name'
		dataType: string
		lineageTag: ed33c2c2-bac7-44ea-8591-614f3217d13a
		summarizeBy: none
		sourceColumn: Priority Name

		annotation SummarizationSetBy = Automatic

	column 'Created Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 56c0e5e4-750a-4ad7-a5b8-11262ded477a
		summarizeBy: none
		sourceColumn: Created Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Updated Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: faedf7c1-65b5-47a2-9c74-7a7fd3979b39
		summarizeBy: none
		sourceColumn: Updated Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Planned Start Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 483603bb-2fdf-4eed-931d-cb75c25878ce
		summarizeBy: none
		sourceColumn: Planned Start Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Planned End Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: d7b80457-dbd6-488e-bbf7-91b785fcf0a9
		summarizeBy: none
		sourceColumn: Planned End Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Actual Start Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 3130ebc5-0cda-4487-b061-8b8e3c9f2522
		summarizeBy: none
		sourceColumn: Actual Start Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Actual End Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: b171308d-50da-4ada-acc6-18e0b6514320
		summarizeBy: none
		sourceColumn: Actual End Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Missing Planned Dates'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 1e1220d8-dc05-4bf3-84cf-4bc259750788
		summarizeBy: none
		sourceColumn: Missing Planned Dates

		annotation SummarizationSetBy = Automatic

	column Summary
		dataType: string
		lineageTag: dc145ac3-9d35-47c3-8686-4a730bd65d36
		summarizeBy: none
		sourceColumn: Summary

		annotation SummarizationSetBy = Automatic

	column 'Display Label'
		dataType: string
		lineageTag: e5d127ab-1143-4dda-a27d-8a29370c7238
		summarizeBy: none
		sourceColumn: Display Label

		annotation SummarizationSetBy = Automatic

	column 'Acceptance Criteria'
		dataType: string
		lineageTag: e2cc496e-12d9-461e-bfdc-5ac9a9dc039c
		summarizeBy: none
		sourceColumn: Acceptance Criteria

		annotation SummarizationSetBy = Automatic

	column 'Jira URL'
		dataType: string
		lineageTag: 39e45a23-6419-488a-8d31-e2a140e3e895
		dataCategory: WebUrl
		summarizeBy: none
		sourceColumn: Jira URL

		annotation SummarizationSetBy = Automatic

	column Description
		dataType: string
		lineageTag: 20b75368-88ba-420a-9469-87511e1166d9
		summarizeBy: none
		sourceColumn: Description

		annotation SummarizationSetBy = Automatic

	partition 'Dim Issue' = m
		mode: import
		source =
				let
				  Source = Sql.Database("cekvmk67pvoetale6vvoo5wfji-brlvcnhvridetpgxmhh6wmlcw4.datawarehouse.fabric.microsoft.com", "gold"),
				    gold_dim_issue = Source{[Schema="gold",Item="dim_issue"]}[Data],
				    RenamedColumns = Table.TransformColumnNames( gold_dim_issue, each Text.Replace(_, "_", " ")),
				    #"Removed Columns" = Table.RemoveColumns(RenamedColumns,{"Test Steps", "Test Type"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Exception

	annotation PBI_NavigationStepName = Navigation

