/// The linked side of Bridge Issue Link - a role-playing copy of Dim Issue so an issue can filter both the anchor and the linked end of a link
table 'Linked Issue'
	lineageTag: 2f8b1a67-9c4d-4e20-8a31-6d5e7c9f0b21

	column 'Issue Key'
		dataType: string
		isHidden
		lineageTag: 3a9c2b78-ad5e-4f31-9b42-7e6f8d0a1c32
		summarizeBy: none
		sourceColumn: Issue Key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Issue Code'
		dataType: string
		lineageTag: 4bad3c89-be6f-4042-ac53-8f709e1b2d43
		summarizeBy: none
		sourceColumn: Issue Code

		annotation SummarizationSetBy = Automatic

	column Summary
		dataType: string
		lineageTag: 5cbe4d9a-cf70-4153-bd64-90810f2c3e54
		summarizeBy: none
		sourceColumn: Summary

		annotation SummarizationSetBy = Automatic

	column 'Issue Type Name'
		dataType: string
		lineageTag: 6dcf5eab-d081-4264-ce75-a1920f3d4f65
		summarizeBy: none
		sourceColumn: Issue Type Name

		annotation SummarizationSetBy = Automatic

	column 'Status Name'
		dataType: string
		lineageTag: 7ed06fbc-e192-4375-df86-b2a3104e5076
		summarizeBy: none
		sourceColumn: Status Name

		annotation SummarizationSetBy = Automatic

	column 'Priority Name'
		dataType: string
		lineageTag: 8fe170cd-f2a3-4486-e097-c3b421506187
		summarizeBy: none
		sourceColumn: Priority Name

		annotation SummarizationSetBy = Automatic

	column 'Jira URL'
		dataType: string
		lineageTag: 90f281de-03b4-4597-f108-d4c532617298
		dataCategory: WebUrl
		summarizeBy: none
		sourceColumn: Jira URL

		annotation SummarizationSetBy = Automatic

	partition 'Linked Issue' = m
		mode: import
		source =
				let
				  Source = Sql.Database("cekvmk67pvoetale6vvoo5wfji-brlvcnhvridetpgxmhh6wmlcw4.datawarehouse.fabric.microsoft.com", "gold"),
				    gold_dim_issue = Source{[Schema="gold",Item="dim_issue"]}[Data],
				    RenamedColumns = Table.TransformColumnNames( gold_dim_issue, each Text.Replace(_, "_", " ")),
				    #"Kept Columns" = Table.SelectColumns(RenamedColumns, {"Issue Key", "Issue Code", "Summary", "Issue Type Name", "Status Name", "Priority Name", "Jira URL"})
				in
				    #"Kept Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation
